Revert "Prune tags as well"
This reverts commit 09aa7c819ac4128619ace3c9142e751c3c5fac98.

Git on the relevant Jenkins job apparently predates 2.17.0 which was
released in June 2018.
https://github.com/git/git/blob/master/Documentation/RelNotes/2.17.0.txt#L32-L33

    - master @ 843dcde ..Could not execute git fetch --prune --tags --prune-tags
    error: unknown option `prune-tags'

https://phabricator.endlessm.com/T27103