Prune while fetching
This job has been failing for the last week:

    ----------------------eos-openqa-tests----------------------
    Using /opt/backups/eos-openqa-tests.git
    - master @ 0c013e2 ..Could not execute git fetch
    error: cannot lock ref 'refs/heads/staging': 'refs/heads/staging/T25144-fix-fbe_language_switch-on-ISOs' exists; cannot create 'refs/heads/staging'
    From github.com:endlessm/eos-openqa-tests
     ! [new branch]      staging    -> staging  (unable to update local ref)
    Terminating early

This is because we previously had branches of the form 'staging/*' in
this repo, and we now have only a 'staging' branch (or none). Git
doesn't support both at once, but nothing pruned old staging branches.
Prune 'em.

https://phabricator.endlessm.com/T27103